name: Deploy to Minikube

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.33.1

      - name: Deploy to Minikube
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE_NAME=${DOCKER_USERNAME}/jenkins_pipeline:${IMAGE_TAG}

          # Update the image in the deployment YAML dynamically
          sed -i "s|image: .*|image: $IMAGE_NAME|" deployment.yaml

          # Apply deployment and service
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

          # Show pods and services for verification
          kubectl get pods -A
          kubectl get svc -A


