name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.33.1

      - name: Deploy to Minikube
        run: |
          kubectl apply -f jenkins_pipeline/deployment.yaml
          kubectl apply -f jenkins_pipeline/service.yaml
          kubectl get pods -A
          kubectl get svc -A
